services:
  api:
    container_name: api_sprint4
    image: api_express
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_USER=kamila
      - DB_HOST=db
      - DB=products_management
      - DB_PASSWORD=1234
      - DB_PORT=5432
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kamila
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=products_management
    volumes:
      - ./src/database/sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
